server:
  port: 8081
spring:
  redis:
#    host: "192.168.2.139"
#    port: 6379
    timeout: 5000
    #    集群环境打开下面注释，单机不需要打开
#    cluster:
#    #      集群信息
#     nodes: 192.168.2.139:6380,192.168.2.139:6381,192.168.2.139:6382
#    #      断开后，重连接台数#默认值是5 一般当此值设置过大时，容易报：Too many Cluster redirections
#     maxRedirects: 3
#    commandTimeout: 5000
    sentinel: #配置哨兵
     master: mymaster
     nodes:
      - 192.168.2.139:26380
    lettuce:
      pool:
        max-active: 1024
        max-wait: 10000ms
        max-idle: 200
        min-idle: 5
    password: 123
#  jedis:
#    pool:
#      max-active: 8
#      min-idle: 0
#      max-idle: 8
#    password: root